### ISSUE TITLE
Build error when running with `bindgen` feature flag

### ISSUE THREAD

**Issue by alexbarcelo** [gyscos/zstd-rs#157]
I tried to build the `zstd-rs` and it works. However, when trying to do it with `cargo build --features bindgen` it fails.

I'm a noob and it's probably my fault. However, I am out of ideas.

The stderr with RUST_BACKTRACE=1 is:

```
  --- stderr
  /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
  /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', zstd-safe/zstd-sys/build.rs:31:40
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::expect
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1035:23
     4: build_script_build::generate_bindings
               at ./build.rs:31:20
     5: build_script_build::main
               at ./build.rs:225:5
     6: core::ops::function::FnOnce::call_once
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The `limits.h` file exists but the `# include_next <limits.h>` fails (that is what /usr/include/limits.h contains on line 124). I thought that I was missing some library, but libzstd-dev package is installed. Searching on Google, some people say _something something_ **limits.h** _something something_ **install linux-libc-dev and/or libc6-dev**. But I already installed those and the error persists.

I am on Ubuntu 20.04.4 with the kernel 5.14.0-1044-oem.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The fact that it only fails with the bindgen features is interesting: it means that when compiling zstd normally, everything works (so you should have the proper headers installed), but when parsing these files with bindgen, it fails.

I pushed a commit to update bindgen (from 0.59 to 0.60), _maybe_ it fixes the issue (it shouldn't hurt in any case).

That being said I cannot reproduce the issue, so I also cannot confirm this fixes anything.

You can try installing `libgcc-9-dev` (or a different version to match your installed `gcc`), it should provide a file like `/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h`.

**Comment by alexbarcelo** [comment]
That was fast!

Now it works, it was a `clang` issue as you suspected. I didn't even have clang installed here.

Before installing clang I pull your commit but that did not solve anything.

I installed clang (both clang-12 and libclang-common-12-dev, I don't know if both are required) and now the build finished successfully :)

Thanks
